# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55c3046b011c3b18b00bdd891ce7af518cdf733e7f786f4d368cce48a4f9d3e332adc1cbec82afcb1f36b08838b88a0f57ea2e808485d669ef0c2cd849eb637d

test:
  secret_key_base: 51f4fbc92ddd80f26c3d0e8981ba79bb07d3a233793b7ec8f28bf8828d5b77f6626a7557b5dc0433eeb4901fd3ec4b04ac5658566531c40495a3320a89200107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
